### ISSUE TITLE
GetCreditCardVendor returns incorrect value

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCard#1]
GetCreditCardVendor method should take card number as string and return vendor as string. It should write nothing to console and it shouldnt use such constrcution as Environment.Exit.
GenerateNextCreditCardNumber has similar issue. It should simply return next card number as string.
Please, remove Console & Environment construnctions. Also, do not use goto operator.

**Comment by tiamalist** [comment]
Оператор goto не можна використовувати у всьому коді?

**Comment by kakarotto67** [comment]
at least try not to use it.

**Comment by tiamalist** [comment]
Виправлено, всі конструкції Environment.Exit. замінені на повернення значення строки яка пердавалась у функцію.

**Comment by tiamalist** [comment]
Environment.Exit. замінив на return s;
також видалив всі Console.ReadLine(); щоб програма нечекала на дію користувача,окрім остаттнього оголошеного в функції Main(), також дана конструкція була добавленя тільки для етапу компіляції та перевірки .

**Comment by tiamalist** [comment]
Оновив код, із внесенням поправок
