### ISSUE TITLE
IsCreditCardNumberValid returns true for invalid number

### ISSUE THREAD

**Issue by kakarotto67** [tiamalist/myCreditCard#3]
Check test below.
        [TestCase("35301113333000001")]
        public void IsCreditCardNumberValid_False(string number)
        {
            Assert.IsFalse(CreditCardUtility.IsCreditCardNumberValid(number));
        }

**Comment by tiamalist** [comment]
Функція "IsCreditCardNumberValid" працює правильно вона визначає чи валідний номер, який переданий в якості параметра у функцію, **незалежно** від кількості вказаних символів.
Так само як і функція "GetCreditCardVendor" яка визначає вендора вказаного номера, і іменно в ній і відбувається веревірка на кількість символів які передаються в номері карти. 
![cc](https://cloud.githubusercontent.com/assets/10754962/15266691/115dce74-19b6-11e6-85cb-fdf2b685c266.jpg)
На скріншоті видно що вказний номер "35301113333000001" у функції  "GetCreditCardVendor" повертає False.
![cc1](https://cloud.githubusercontent.com/assets/10754962/15266705/66f130ec-19b6-11e6-8ca3-601e8890824c.jpg)
так як для вказаного вендора кількість символів  -"16". а кількість символів переданих у функцію -"17", тому імя вендора не виводиться на екран.
Кількість символів відповідає вендору:
![cc2](https://cloud.githubusercontent.com/assets/10754962/15266720/13647ff0-19b7-11e6-9987-55fe9d9eb586.jpg)
Результат виконання True.
**Варіант виправлення:**
У всі блоки коду:
![cc3](https://cloud.githubusercontent.com/assets/10754962/15266730/53bae0ee-19b7-11e6-8563-0b4c0ebd1e1e.jpg)
добавити строку:
![image](https://cloud.githubusercontent.com/assets/10754962/15266733/71a92930-19b7-11e6-80c4-382119fb3694.png)
Так щоб програма повідомляла що номер не визначено.

**Comment by tiamalist** [comment]
А також щоб у функцію "IsCreditCardNumberValid" передавався результат виконнання функції "GetCreditCardVendor"(true або false).

**Comment by tiamalist** [comment]
Дописав строку із вказаннням невизначеного вендора, у випанку невідповідності номера до вендора.
Код оновив.
